### PR TITLE
Make use of connectionListener arg passed to createConnection.

### PR DESCRIPTION
**Pull request by canndrew**
net = require("net");
require("abstractsocket")(net);

net.createConnection("\u0000/foo", function() {
    console.log("This gets called now");
});

### CODE REVIEW

**Comment by sidorares** [comment]
Thanks! Do you actually use abstract sockets?

**Comment by canndrew** [comment]
GNUnet uses them. I'm working on a library to talk to GNUnet.

**Comment by sidorares** [comment]
I see. My goal was to create proper C++ addon for abstractsockets support (it's just extra '\0' in the socket name), but I never had enough time to make it and socat works well enough. This could be a good starting point - https://github.com/bnoordhuis/node-unix-dgram

Let me know if you decide to go C++ way

**Comment by canndrew** [comment]
Interesting. I'll use socat for now so long as it works but I might have a go at adapting that library later.

**Comment by sidorares** [comment]
Whoever first :) Binary addon api should be the same as core Socket

**Comment by sidorares** [comment]
published v0.0.3

**Pull request merged**
